### ISSUE TITLE
BUG: Script can't deal with subdomains

### ISSUE THREAD

**Issue by sschueller** [noahbliss/freeipa-sam#1]
If the ```domain``` entered is a subdomain (e.g. ```ldap.example.com```) the script will incorrectly parse it (https://github.com/noahbliss/freeipa-sam/blob/master/freeipa-sam.sh#L39) and freeipa will print ```Missing target entry.``` in the logs as the ```dn``` used it wrong.

**Comment by noahbliss** [comment]
Resolved by @Heidistein in #2
