### ISSUE TITLE
ldaps vs ldap

### ISSUE THREAD

**Issue by ElmarKnipp** [noahbliss/freeipa-sam#5]
Switching to a connection without SSL (option 5) leads to a wrong ldapurl.

Instead of the prefix "ldap" it is switched to "http".

**Comment by noahbliss** [comment]
Should be resolved as https://github.com/noahbliss/freeipa-sam/commit/9dbb9a99ba1abe5e4edcb415f181d63e779d5beb

Thanks for the callout!
